import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { StoreProvider, useStore } from '../app/context/store'
// import { ApolloProvider } from '@apollo/client';
// import client from './apolloClient/apolloClient';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
          {/* <ApolloProvider client={client}> */}
      <UserProvider>
        <StoreProvider>
      <body className={inter.className}>{children}</body>
      </StoreProvider>
      </UserProvider>
      {/* </ApolloProvider> */}
    </html>
  )
}
